### ISSUE TITLE
Translate game

### ISSUE THREAD

**Issue by luanorlandi** [luanorlandi/Swift-Space-Battle#13]
This game welcome any translations. Check before if there is already a language or pull request with the translation.

The languages supported are in `src/file/` directory. Files are in Lua and they contain a table similar to object structure in JavaScript.

To make a new translation, consider these instructions:
- Copy the file `src/file/en.lua` to the same folder. It's recommended to name the file by following [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
- Apply translations by altering each value, keeping the file structure
- Add an import in `src/file/strings.lua`. Examples for this are on the start of file

**Comment by krns** [comment]
I will do german!

**Comment by fc2** [comment]
Can I help with traditional Chinese translation?

**Comment by luanorlandi** [comment]
@fc2 Yes, all languages are welcome!

**Comment by greystate** [comment]
I'll do Danish translation 🤝

**Comment by hndr91** [comment]
Need permission for Bahasa Indonesia Sir !

**Comment by lukyhruska96** [comment]
8cab30c

**Comment by roastchicken** [comment]
I'll do Norwegian (Bokmål).

**Comment by luanorlandi** [comment]
🎉 Thank you all for the translations, they are applied to a new build of the game 🎉

Please have a look at the [game page] in web version to see your language submitted 👍 

I changed the font to be able to use all the different type of characters. But there was 2 languages that still need a specific font for them: Georgian and Chinese.

I will keep them to future use when the game support a font switch feature.

[game page]: https://luanorlandi.github.io/Swift-Space-Battle/
